"""Incident report data model — the final output of the summarization pipeline.

An IncidentReport is the structured, analyst-ready document that combines
raw incident data with LLM-generated natural language analysis. This is
what appears in the dashboard, gets emailed to the SOC team, or feeds
into a ticketing system (ServiceNow, Jira, PagerDuty).

The report format follows industry standards:
    - NIST SP 800-61 (Computer Security Incident Handling Guide)
    - SANS Incident Handler's Handbook
    - Palo Alto Cortex XSIAM incident report structure
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class IoC(BaseModel):
    """Indicator of Compromise — actionable threat intelligence."""

    type: str              # ip, port, domain, hash, signature
    value: str             # The actual indicator
    context: str = ""      # Why this is suspicious
    action: str = ""       # block, monitor, investigate


class ResponseAction(BaseModel):
    """Recommended response action for the analyst."""

    priority: int          # 1 = immediate, 2 = urgent, 3 = standard
    action: str            # What to do
    rationale: str = ""    # Why this matters


class IncidentReport(BaseModel):
    """Complete incident report — the final deliverable."""

    # Metadata
    incident_id: str
    generated_at: datetime = Field(default_factory=datetime.now)
    generator: str = "template"  # "template" or "llm:<model_name>"

    # Incident context
    severity: str
    title: str
    event_count: int = 0
    duration_seconds: float = 0.0
    first_seen: datetime | None = None
    last_seen: datetime | None = None

    # LLM-generated content
    executive_summary: str = ""
    timeline_narrative: str = ""
    impact_assessment: str = ""
    technical_details: str = ""

    # Structured data
    iocs: list[IoC] = Field(default_factory=list)
    response_actions: list[ResponseAction] = Field(default_factory=list)
    attack_stages: list[str] = Field(default_factory=list)
    affected_assets: list[str] = Field(default_factory=list)

    # MITRE ATT&CK mapping
    mitre_techniques: list[str] = Field(default_factory=list)

    def to_markdown(self) -> str:
        """Render the report as a Markdown document."""
        lines = [
            f"# Incident Report: {self.incident_id}",
            "",
            f"**Severity:** {self.severity.upper()}  ",
            f"**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M:%S')}  ",
            f"**Generator:** {self.generator}  ",
            "",
            "---",
            "",
            f"## {self.title}",
            "",
            "### Executive Summary",
            "",
            self.executive_summary,
            "",
        ]

        if self.timeline_narrative:
            lines.extend([
                "### Timeline",
                "",
                self.timeline_narrative,
                "",
            ])

        if self.impact_assessment:
            lines.extend([
                "### Impact Assessment",
                "",
                self.impact_assessment,
                "",
            ])

        if self.technical_details:
            lines.extend([
                "### Technical Details",
                "",
                self.technical_details,
                "",
            ])

        if self.iocs:
            lines.extend([
                "### Indicators of Compromise (IoCs)",
                "",
                "| Type | Value | Context | Action |",
                "|------|-------|---------|--------|",
            ])
            for ioc in self.iocs:
                lines.append(f"| {ioc.type} | `{ioc.value}` | {ioc.context} | {ioc.action} |")
            lines.append("")

        if self.response_actions:
            lines.extend([
                "### Recommended Response Actions",
                "",
            ])
            for action in sorted(self.response_actions, key=lambda a: a.priority):
                priority_label = {1: "[!] IMMEDIATE", 2: "[*] URGENT", 3: "[-] STANDARD"}.get(
                    action.priority, "[ ] INFO"
                )
                lines.append(f"- **{priority_label}:** {action.action}")
                if action.rationale:
                    lines.append(f"  - *{action.rationale}*")
            lines.append("")

        if self.mitre_techniques:
            lines.extend([
                "### MITRE ATT&CK Mapping",
                "",
                ", ".join(f"`{t}`" for t in self.mitre_techniques),
                "",
            ])

        lines.extend([
            "---",
            "",
            f"*Report generated by SOC Log Analyzer | "
            f"{self.event_count} events analyzed | "
            f"Duration: {self._format_duration()}*",
        ])

        return "\n".join(lines)

    def _format_duration(self) -> str:
        if self.duration_seconds <= 0:
            return "instantaneous"
        mins = int(self.duration_seconds // 60)
        secs = int(self.duration_seconds % 60)
        if mins > 60:
            hours = mins // 60
            mins = mins % 60
            return f"{hours}h {mins}m"
        return f"{mins}m {secs}s" if mins else f"{secs}s"
